apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopflow
  labels:
    app: order-service
    tier: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: microservice
    spec:
      containers:
        - name: order-service
          image: shopflow-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: DB_HOST
              value: "order-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "order_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: POSTGRES_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: PRODUCT_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: PAYMENT_SERVICE_URL
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: KEYCLOAK_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_SERVICE_NAME
              value: "order-service"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shopflow
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  selector:
    app: order-service
